# Generated by Django 5.0.6 on 2024-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('payment_type_name', models.CharField(max_length=30)),
                ('payment_type_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'payment_types',
            },
        ),
    ]
