# Generated by Django 5.0.6 on 2024-06-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=30)),
                ('category_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
